// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['app']['App']['Cancel']();
}

export function ConvertImages(arg1) {
  return window['go']['app']['App']['ConvertImages'](arg1);
}

export function ConvertVideo(arg1) {
  return window['go']['app']['App']['ConvertVideo'](arg1);
}

export function CopyOutput(arg1) {
  return window['go']['app']['App']['CopyOutput'](arg1);
}

export function PickFolder() {
  return window['go']['app']['App']['PickFolder']();
}

export function PickImages() {
  return window['go']['app']['App']['PickImages']();
}

export function PickVideo() {
  return window['go']['app']['App']['PickVideo']();
}

export function PreviewHandler() {
  return window['go']['app']['App']['PreviewHandler']();
}

export function RevealOutput(arg1) {
  return window['go']['app']['App']['RevealOutput'](arg1);
}

export function SetPreview(arg1) {
  return window['go']['app']['App']['SetPreview'](arg1);
}
