// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {http} from '../models';

export function Cancel():Promise<void>;

export function ConvertImages(arg1:app.ImagesRequest):Promise<app.ConvertResult>;

export function ConvertVideo(arg1:app.VideoRequest):Promise<app.ConvertResult>;

export function CopyOutput(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PickImages():Promise<Array<app.ImageInfo>>;

export function PickVideo():Promise<app.VideoInfo>;

export function PreviewHandler():Promise<http.Handler>;

export function RevealOutput(arg1:string):Promise<void>;

export function SetPreview(arg1:string):Promise<void>;
